import Category from "./category/Category";
import PLP from "./Product-Listing-Page/PLP";
import Loader from "./loader/Loader";
import Nav from "./nav/Nav";
import Product from "./product/Product";
import Error from "./error/Error";
import PDP from "./product-description-page/PDP";
import MiniCart from "./cart/minicart/MiniCart";
import Cart from "./cart/cart/Cart";
export {Category ,PLP, Loader, Nav, Product, Error, PDP, MiniCart, Cart};
